### ISSUE TITLE
How to create user account

### ISSUE THREAD

**Issue by soodrohit** [oslabs-beta/Kafka-Sonar#44]
I have tried multiple times to create a user account but it keeps rejecting? Is there a default admin account that you can use to login for first time users?

**Comment by mjsway** [comment]
@soodrohit 

Can you confirm there's a timescaledb container running under Kafka Sonar like in the below image:
![image](https://github.com/user-attachments/assets/dd5d4847-52e3-469d-91a7-902e58030aa3)

**Comment by soodrohit** [comment]
thanks..
